# Generated by Django 5.2.4 on 2025-10-26 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0003_userloginlog_channel_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="报告编号"
                    ),
                ),
                (
                    "assess_type",
                    models.CharField(
                        help_text="如：情绪测评、人格测评",
                        max_length=64,
                        verbose_name="评估类型",
                    ),
                ),
                (
                    "assess_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="评估日期"
                    ),
                ),
                (
                    "multimodal_data",
                    models.JSONField(
                        help_text="存储文本、语音等特征的JSON数据",
                        verbose_name="多模态数据",
                    ),
                ),
                ("core_conclusion", models.TextField(verbose_name="核心结论")),
                (
                    "risk_level",
                    models.SmallIntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高")],
                        default=1,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "report_status",
                    models.SmallIntegerField(
                        choices=[(1, "草稿"), (2, "已完成"), (3, "已归档")],
                        default=1,
                        verbose_name="报告状态",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_assessor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评估人",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被评估人",
                    ),
                ),
            ],
            options={
                "verbose_name": "评估报告",
                "verbose_name_plural": "评估报告",
            },
        ),
        migrations.CreateModel(
            name="InterventionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "plan_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="方案编号"
                    ),
                ),
                (
                    "plan_title",
                    models.CharField(max_length=128, verbose_name="方案标题"),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        help_text="如：认知行为疗法、正念训练",
                        max_length=64,
                        verbose_name="干预类型",
                    ),
                ),
                (
                    "target_issue",
                    models.TextField(
                        help_text="针对评估报告的问题描述", verbose_name="核心问题"
                    ),
                ),
                (
                    "specific_measures",
                    models.JSONField(
                        help_text="分阶段干预步骤的JSON数据", verbose_name="具体措施"
                    ),
                ),
                ("expected_effect", models.TextField(verbose_name="预期效果")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "plan_status",
                    models.SmallIntegerField(
                        choices=[(1, "待执行"), (2, "进行中"), (3, "已完成")],
                        default=1,
                        verbose_name="方案状态",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "planner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_planner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="方案制定人",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_report",
                        to="personalize.assessmentreport",
                        verbose_name="关联评估报告",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="干预对象",
                    ),
                ),
            ],
            options={
                "verbose_name": "干预方案",
                "verbose_name_plural": "干预方案",
            },
        ),
    ]
