# Generated by Django 5.2.4 on 2025-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_userloginlog_channel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="file_type",
            field=models.CharField(
                default="text", max_length=255, verbose_name="File type"
            ),
            preserve_default=False,
        ),
    ]
