# Generated by Django 5.2.4 on 2025-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_uploadfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file_type",
            field=models.CharField(max_length=255, verbose_name="文件类型"),
        ),
    ]
