# Generated by Django 5.2.4 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_alter_uploadfile_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="medical_record_no",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name="Medical Record Number"),
        ),
    ]

