# Generated by Django 5.2.4 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_add_medical_record_no_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="description",
            field=models.TextField(blank=True, help_text="File description", null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to="system.userinfo",
                verbose_name="User",
            ),
        ),
    ]

