# Generated by Django 5.2.4 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_add_user_and_description_to_uploadfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="medical_record_no",
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Medical Record Number"),
        ),
    ]

