# Generated by Django 5.2.4 on 2025-11-22 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0005_alter_uploadfile_file_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "medical_record_no",
                    models.CharField(max_length=50, unique=True, verbose_name="病历号"),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=50, verbose_name="病人姓名"),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="出生日期")),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="就诊科室"
                    ),
                ),
                (
                    "first_visit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="首次就诊时间"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "病人信息",
                "verbose_name_plural": "病人信息",
            },
        ),
        migrations.CreateModel(
            name="EegBdfData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "bdf_file_path",
                    models.CharField(max_length=255, verbose_name="文件存储路径"),
                ),
                (
                    "bdf_file_name",
                    models.CharField(max_length=100, verbose_name="文件名"),
                ),
                (
                    "collect_device",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="采集设备型号",
                    ),
                ),
                ("collect_time", models.DateTimeField(verbose_name="数据采集开始时间")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未处理"), (1, "已分析"), (2, "异常")],
                        default=0,
                        verbose_name="数据状态",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eeg_bdfs",
                        to="biofeedback.patientinfo",
                        verbose_name="关联病人",
                    ),
                ),
            ],
            options={
                "verbose_name": "脑电BDF数据",
                "verbose_name_plural": "脑电BDF数据",
            },
        ),
        migrations.CreateModel(
            name="PdfReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "report_file_path",
                    models.CharField(max_length=255, verbose_name="文件存储路径"),
                ),
                (
                    "report_file_name",
                    models.CharField(max_length=100, verbose_name="文件名"),
                ),
                (
                    "report_type",
                    models.CharField(max_length=50, verbose_name="报告类型"),
                ),
                (
                    "report_version",
                    models.CharField(max_length=20, verbose_name="报告版本"),
                ),
                ("generate_time", models.DateTimeField(verbose_name="报告生成时间")),
                (
                    "bdf_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdf_reports",
                        to="biofeedback.eegbdfdata",
                        verbose_name="关联BDF数据",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdf_reports",
                        to="biofeedback.patientinfo",
                        verbose_name="关联病人",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF报告",
                "verbose_name_plural": "PDF报告",
            },
        ),
        migrations.AddIndex(
            model_name="patientinfo",
            index=models.Index(
                fields=["patient_name"], name="biofeedback_patient_c0a0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientinfo",
            index=models.Index(
                fields=["department"], name="biofeedback_departm_e98537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eegbdfdata",
            index=models.Index(
                fields=["collect_time"], name="biofeedback_collect_a0a168_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eegbdfdata",
            index=models.Index(fields=["status"], name="biofeedback_status_8d96eb_idx"),
        ),
        migrations.AddIndex(
            model_name="pdfreport",
            index=models.Index(
                fields=["generate_time"], name="biofeedback_generat_9645cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfreport",
            index=models.Index(
                fields=["report_type"], name="biofeedback_report__226a05_idx"
            ),
        ),
    ]
